// generated by stringer -type=Type; DO NOT EDIT

package proxy

import "fmt"

const _Type_name = "TCPHTTPUnknownType"

var _Type_index = [...]uint8{0, 3, 7, 18}

func (i Type) String() string {
	if i < 0 || i+1 >= Type(len(_Type_index)) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
